# https://awstip.com/how-to-continuously-build-deploy-a-python-web-app-on-aws-with-github-actions-b20e195c9006

name: Deploy Python Web App

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Step to checkout code in GitHub Actions

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install gunicorn


      - name: Deploy to AWS
        env:
          EC2_IP: ${{secrets.EC2_IP}}
          AWS_SSH_KEY: ${{secrets.AWS_SSH_KEY}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "${AWS_SSH_KEY}" > ec2-key.pem
          chmod 600 ec2-key.pem
          
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@$EC2_IP << EOF
          git pull origin main
          cd labs020925
          source venv/bin/activate
          pip install Flask
          pip install gunicorn
          sudo systemctl restart labs020925
          EOF
          rm ec2-key.pem
